// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Ervins

package repopolicy_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/resoltico/pdfconcat/internal/repopolicy"
)

const (
	sourceLimitLineLimit       = 1000
	sourceLimitTypeLimit       = 20
	sourceLimitFixture         = "fixture.go"
	sourceLimitTrailingComment = " // comment"
)

func sourceLimitFunctions(count int, trailing string) string {
	var source strings.Builder
	for index := range count {
		fmt.Fprintf(&source, "func value%d() {}%s\n", index, trailing)
	}

	return source.String()
}

func TestSourceLimitsCountPhysicalCodeLines(t *testing.T) {
	t.Parallel()

	for _, test := range []struct{ name, prefix, trailing string }{
		{"ordinary", "package p\n", ""},
		{"trailing comments", "package p\n", sourceLimitTrailingComment},
		{"inline block comments", "package p /* first */ /* second */\n", " /* comment */"},
		{"multiline endpoints", "/* comment\n\n*/ package p /* comment\n\n*/\n", sourceLimitTrailingComment},
		{"display directives", "//line /tmp/display.go:1\npackage p\n", sourceLimitTrailingComment},
		{
			"generated tagged fixture",
			"// Code generated by a fixture. DO NOT EDIT.\n//go:build never_selected\n\npackage p\n",
			sourceLimitTrailingComment,
		},
		{
			"CRLF standalone blocks",
			"/* comment\r\n" + strings.Repeat("comment\r\n", sourceLimitLineLimit+1) + "*/\r\npackage p\r\n",
			" /* one */ /* two */",
		},
		{"CRLF endpoints", "/* comment\r\n*/ package p /* other\r\n*/\r\n", sourceLimitTrailingComment},
		{"CRLF", "package p\r\n", " // comment\r"},
	} {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			accepted := test.prefix + sourceLimitFunctions(sourceLimitLineLimit-1, test.trailing)
			if issues, err := repopolicy.SourceLimitIssues(sourceLimitFixture, []byte(accepted)); err != nil || len(issues) != 0 {
				t.Fatalf("boundary rejected: %v, %v", issues, err)
			}

			rejected := accepted + "func overflow() {} // comment\n"

			issues, err := repopolicy.SourceLimitIssues(sourceLimitFixture, []byte(rejected))
			if err != nil || len(issues) != 1 || !strings.Contains(issues[0], "1001 code-bearing lines") {
				t.Fatalf("oversize source escaped: %v, %v", issues, err)
			}
		})
	}
}

func TestSourceLimitsPreserveRawLiteralLines(t *testing.T) {
	t.Parallel()

	source := "package p\nvar value = `\n" + strings.Repeat("// comment-shaped literal\n", sourceLimitLineLimit-3) + "`\n"
	if issues, err := repopolicy.SourceLimitIssues(sourceLimitFixture, []byte(source)); err != nil || len(issues) != 0 {
		t.Fatalf("raw literal boundary rejected: %v, %v", issues, err)
	}

	source = strings.Replace(source, "`\n", "\n/* literal */\n`\n", 1)

	issues, err := repopolicy.SourceLimitIssues(sourceLimitFixture, []byte(source))
	if err != nil || len(issues) != 1 || !strings.Contains(issues[0], "1001 code-bearing lines") {
		t.Fatalf("raw literal code was erased: %v, %v", issues, err)
	}
}

func TestSourceLimitsRetainExportedTypeDeclarationLimit(t *testing.T) {
	t.Parallel()

	for _, shape := range []string{"type Shape%d struct{}\n", "type Shape%d = int\n", "type Shape%d[T any] []T\n", "type Σhape%d int\n"} {
		t.Run(shape, func(t *testing.T) {
			t.Parallel()

			var source strings.Builder
			source.WriteString("package p\ntype σhape int\n")

			for index := range sourceLimitTypeLimit {
				fmt.Fprintf(&source, shape, index)
			}

			issues, err := repopolicy.SourceLimitIssues(sourceLimitFixture, []byte(source.String()))
			if err != nil || len(issues) != 0 {
				t.Fatalf("type boundary rejected: %v, %v", issues, err)
			}

			source.WriteString("type Overflow int\n")

			issues, err = repopolicy.SourceLimitIssues(sourceLimitFixture, []byte(source.String()))
			if err != nil || len(issues) != 1 || !strings.Contains(issues[0], "21 exported type declarations") {
				t.Fatalf("exported declarations escaped: %v, %v", issues, err)
			}
		})
	}
}

func TestSourceLimitScanCoversPhysicalOwnedSources(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	names := []string{"untracked.go", "pkg/testdata/fixture.go", ".hidden/generated.go", "pkg/dist/large.go", "pkg/.tools/large_test.go"}
	source := "//go:build never_selected\n\npackage p\n" + sourceLimitFunctions(sourceLimitLineLimit, sourceLimitTrailingComment)

	for _, name := range names {
		file := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(file), 0o750); err != nil {
			t.Fatal(err)
		}

		if err := os.WriteFile(file, []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	issues, err := repopolicy.ScanSourceLimits(root)
	if err != nil || len(issues) != len(names) {
		t.Fatalf("owned sourceLimit discovery: %v, %v", issues, err)
	}
}

func TestSourceLimitsFailWhenSourceCannotBeEstablished(t *testing.T) {
	t.Parallel()

	if _, err := repopolicy.SourceLimitIssues("broken.go", []byte("package p\nfunc {")); err == nil {
		t.Fatal("malformed source accepted")
	}

	if _, err := repopolicy.ScanSourceLimits(t.TempDir()); err == nil {
		t.Fatal("empty source inventory accepted")
	}

	if _, err := repopolicy.ScanSourceLimits(filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Fatal("unavailable root accepted")
	}
}
